[pytest]
pythonpath = . backend
testpaths = tests
python_files = test_*.py
addopts = -s
markers =
    production: marks tests that require production database connection (deselect with '-m "not production"')